dist: precise
language: node_js
node_js:
  - "8.2.1"

before_script:
  - npm i -g yarn && yarn
  - npm install -g firebase-tools

script:
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN